#!/bin/bash
set -e

# extract d.ts files using typescript
tsc --project tsconfig.types.json

# bundle them with rollup
NODE_OPTIONS=--max_old_space_size=16384 rollup --config rollup/rollup.types.config.ts --configPlugin 'typescript={tsconfig: `tsconfig.rollup-config-types.json`}'

# remove temporary files
rm -rf ./dist/types

# copy vscode required namespaces
cp vscode/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts dist/main/
