#!/bin/bash
set -e

vscodeRef=$(cat './node_modules/monaco-editor/package.json' | jq -r '.["vscodeRef"]')
cat <<< "$(jq ".config.vscode.ref = \"$vscodeRef\"" package.json)" > package.json

monaco_esm_directory="`pwd`/node_modules/monaco-editor/esm"
output_directory="`pwd`/vscode"
extension_output_directory="`pwd`/vscode-default-extensions"
patch_file="`pwd`/scripts/vscode.patch"
editor_patch_file="`pwd`/monaco-editor-treemending.patch"
version_info=$output_directory/version.info

if [[ -e $version_info && $(cat $version_info) == $vscodeRef ]]; then
    echo "vscode version $vscodeRef is already installed. Aborting..."
    exit 0
else
    echo "vscode version $vscodeRef is not available. Installing..."
fi

rm -rf $output_directory

build_directory=`mktemp -d`
echo "Downloading vscode $vscodeRef in $build_directory..."

curl -L --max-redirs 5 https://github.com/Microsoft/vscode/tarball/$vscodeRef | tar -xz -C $build_directory --strip-components=1 microsoft-vscode-${vscodeRef:0:7}
vscodeVersion=$(cat "$build_directory/package.json" | jq -r '.["version"]')
cat <<< "$(jq ".config.vscode.version = \"$vscodeVersion\"" package.json)" > package.json

cd $build_directory

echo "Installing vscode dependencies..."
yarn config set ignore-engines
yarn install --ignore-scripts
yarn postinstall || true

echo "Patching vscode..."
patch -p1 < $patch_file

# build editor without treeshaking to generate the treemending patch
echo "Installing build dependencies"
cd build
yarn install --ignore-engines
cd ..

mkdir -p editor-patch
cp -R $monaco_esm_directory editor-patch/a
cp -R $monaco_esm_directory editor-patch/b
## Change shake level from ClassMembers to Files
sed -i'' -e 's/shakeLevel: 2/shakeLevel: 0/g' build/gulpfile.editor.js
yarn gulp editor-distro
cd out-monaco-editor-core/esm/
rsync -R $(find . -name \*.js) ../../editor-patch/b
cd ../../editor-patch
diff -urN -x '*.map' a b > "$editor_patch_file" || true
cd ..
# end treemending patch

# build and copy default extensions
yarn compile-web || true
yarn gulp compile-extension-media
rm -rf $extension_output_directory
cp -R extensions "$extension_output_directory"

# transform to relative imports, replace ESM comments and vs/css! imports
cat << EOF | node -
	require('./build/lib/standalone').createESMSourcesAndResources2({
		srcFolder: './src',
		outFolder: './src',
		outResourcesFolder: './resources',
		ignores: [
			'inlineEntryPoint:0.ts',
			'inlineEntryPoint:1.ts',
			'vs/loader.js',
			'vs/base/worker/workerMain.ts',
		],
		renames: {
		}
	});
EOF
cd resources
rsync -R $(find . -name \*.js) ../src/
cd ..

cd src

# Remove useless files
rm -rf `find . -name '*.test.ts' -o -name 'test' -o -name 'electron-browser'`
rm -rf vs/code

mkdir -p $output_directory
echo $vscodeRef > $version_info

echo "Building vscode..."
NODE_OPTIONS=--max-old-space-size=8192 npx tsc --declaration --importHelpers --module es2020 --preserveConstEnums --outDir "$output_directory"
# Copy files that are already built
find ./ \( -name '*.js' -o -name '*.d.ts' -o -name '*.css' -o -name '*.mp3' -o -name '*.svg' -o -name '*.html' \) -exec rsync -R \{\} "$output_directory/src" \;

echo "Cleaning..."
rm -rf $build_directory
